// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcsEnq0n9uS6DiJJbnqTMvBTxeHzjn1BE',
    appId: '1:693150012196:web:ed1b32e46c3127a9bd19b1',
    messagingSenderId: '693150012196',
    projectId: 'quizmaker2-565b6',
    authDomain: 'quizmaker2-565b6.firebaseapp.com',
    databaseURL: 'https://quizmaker2-565b6-default-rtdb.firebaseio.com',
    storageBucket: 'quizmaker2-565b6.appspot.com',
    measurementId: 'G-QMXV08600L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ7rcxVAMvP4gNFshDkGOwb-_jgbdslt8',
    appId: '1:693150012196:android:0f1d829f7ed18aaebd19b1',
    messagingSenderId: '693150012196',
    projectId: 'quizmaker2-565b6',
    databaseURL: 'https://quizmaker2-565b6-default-rtdb.firebaseio.com',
    storageBucket: 'quizmaker2-565b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-iPNLRo9f0H4EtY_LvbEFuU1NgIZd2Uk',
    appId: '1:693150012196:ios:003e0590e1885f08bd19b1',
    messagingSenderId: '693150012196',
    projectId: 'quizmaker2-565b6',
    databaseURL: 'https://quizmaker2-565b6-default-rtdb.firebaseio.com',
    storageBucket: 'quizmaker2-565b6.appspot.com',
    androidClientId: '693150012196-hppogcge3ajul245cfgghlv6q63b4kmr.apps.googleusercontent.com',
    iosClientId: '693150012196-7rdb8412svm4ouavdc2pfi809vsa2p23.apps.googleusercontent.com',
    iosBundleId: 'com.example.traveler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-iPNLRo9f0H4EtY_LvbEFuU1NgIZd2Uk',
    appId: '1:693150012196:ios:003e0590e1885f08bd19b1',
    messagingSenderId: '693150012196',
    projectId: 'quizmaker2-565b6',
    databaseURL: 'https://quizmaker2-565b6-default-rtdb.firebaseio.com',
    storageBucket: 'quizmaker2-565b6.appspot.com',
    androidClientId: '693150012196-hppogcge3ajul245cfgghlv6q63b4kmr.apps.googleusercontent.com',
    iosClientId: '693150012196-7rdb8412svm4ouavdc2pfi809vsa2p23.apps.googleusercontent.com',
    iosBundleId: 'com.example.traveler',
  );
}
