name: CI on Traveler

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - dev
      - production

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '2.10.2'
          channel: 'stable'
          architecture: 'x64'
      - run: |
          flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: traveler-release.apk
          path: build/app/outputs/apk/release/app-release.apk
      - uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  # Replace with your desired tag name
          name: Traveler Release
          body: This is a release for Traveler.
      - uses: ncipollo/release-action@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/apk/release/app-release.apk
          asset_name: traveler-release.apk
          asset_content_type: application/vnd.android.package-archive
          token: ${{ secrets.TRAVELER_TOKEN }}  